name: tinder_pets
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dart_frog: ^0.0.1-dev
  dart_jsonwebtoken: ^2.4.1
  freezed_annotation: ^2.0.3
  jaguar_jwt: ^3.0.0
  json_annotation: ^4.5.0
  hive: ^2.2.3
  uuid: ^3.0.6
  faker: ^2.0.0

dev_dependencies:
  analyzer: ^4.2.0
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  hive_generator: ^1.1.3
  json_serializable: ^6.2.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1
